Memochka/Models/Entities/Meme.cs
 using System.ComponentModel.DataAnnotations;

 namespace Memochka.Models.Entities
{
    public record Meme
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Title is required")]
        [StringLength(200, ErrorMessage = "The title cannot be more than 200 characters long")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Meaning is required")]
        public string Meaning { get; set; }

        [Required(ErrorMessage = "Origins is required")]
        public string Origins { get; set; }

        [Required(ErrorMessage = "Year is required")]
        [Range(2007,2023, ErrorMessage = "Year must be in range between 2007 and 2023")]
        public int Year { get; set; }
        public DateTime PublicationDate { get; set; }
        public bool IsApproved { get; set; }
        public int Views { get; set; }
        public int UserId { get; set; }
        public int CategoryId { get; set; }


        public List<MemePicture> MemePictures { get; set; }
        public MemeCategory MemeCategory { get; set; }
        public User User { get; set; }
    }
}

Memochka/Controllers/ArticleController.cs
using Memochka.Models.Entities;
using Memochka.Models.MemochkaDbContext;
using Memochka.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Memochka.Controllers
{
    public class ArticleController : Controller
    {
        private readonly IArticle _articleService;
        private readonly MemochkaContext _context;

        public ArticleController(IArticle articleService, MemochkaContext context)
        {
            _articleService = articleService;
            _context = context;
        }

        public IActionResult Articles() => View();
        [Authorize]
        public IActionResult CreateArticlePage() => View();
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> CreateArticle(Article article)
        {
            var userLogin = HttpContext.User.Identity.Name;
            if (!Request.Form.Files.Any())
            {
                ModelState.AddModelError("Title", "Main Image could not be null");
                return RedirectToAction("CreateArticlePage", article);
            }
            var creteArticleParagraph = await _articleService.CreateArticleAsync(article, userLogin, Request.Form.Files);
            if (!creteArticleParagraph.IsSuccess)
            {
                ModelState.AddModelError("Title",creteArticleParagraph.ErrorMessage);
                return RedirectToAction("CreateArticlePage", article);
                //return BadRequest(creteArticleParagraph.ErrorMessage);
            }
            return RedirectToAction("ProfilePage", "User");
        }

        public async Task<IActionResult> ArticlePage(int id)
        {
            var articleViews = await _articleService.UpArticleViewsAsync(id);
            if (!articleViews.IsSuccess)
                return BadRequest(articleViews.ErrorMessage);
            Article article = new Article();
            if (User.IsInRole("Admin"))
            {
                article = _context.Articles
                    .Where(a => a.Id == id)
                    .Include(u => u.User)
                    .Include(u => u.ArticleParagraphs)
                    .FirstOrDefault();
            }
            else
            {
                article = _context.Articles
                    .Where(a => a.Id == id && a.IsApproved == true)
                    .Include(u => u.User)
                    .Include(u => u.ArticleParagraphs)
                    .FirstOrDefault();
            }
            if (article==null||article.Id==0)
                return NotFound("The article does not exist or has not been approved by the moderator");
            return View(article);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> PublishArticle(int id)
        {
            var publishedArticle = await _articleService.PublishArticle(id);
            if (!publishedArticle.IsSuccess)
                return BadRequest(publishedArticle.ErrorMessage);
            return RedirectToAction("AdminPanel", "User");
        }
    }
}

Memochka/Controllers/MemeController.cs
using Memochka.Models.Entities;
using Memochka.Models.MemochkaDbContext;
using Memochka.Services;
using Memochka.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;

namespace Memochka.Controllers
{
    public class MemeController : Controller
    {
        private readonly IMeme _memeService;
        private readonly MemochkaContext _context;

        public MemeController(IMeme memeService, MemochkaContext context)
        {
            _memeService = memeService;
            _context = context;
        }
        [Authorize]
        public IActionResult CreateMemePage() => View();
        public IActionResult MemesOffer() => View();
        public async Task<IActionResult> Memes(string category, int year)
        {
            var memes = await _memeService.GetOrderedemesAsync(category, year);
            if (!memes.IsSuccess)
                return BadRequest(memes.ErrorMessage);
            return View(memes.MemesList);
        }
        [Authorize]
        public async Task<IActionResult> CreateMeme(Meme meme)
        {
            var userLogin = HttpContext.User.Identity.Name;
            if (!Request.Form.Files.Any())
                return RedirectToAction("CreateMemePage", meme);
            var memeService = await _memeService.CreateMemeAsync(userLogin, meme, Request.Form.Files);
            if (!memeService.IsSuccess)
                return BadRequest(memeService.ErrorMessage);
            return RedirectToAction("ProfilePage", "User");
        }

        public async Task<IActionResult> MemePage(int id)
        {
            var memeViews = await _memeService.UpMemeViewsAsync(id);
            if (!memeViews.IsSuccess)
                return BadRequest(memeViews.ErrorMessage);
            Meme meme = new Meme();
            if (User.IsInRole("Admin"))
            {
                meme = _context.Memes
                    .Where(m => m.Id == id)
                    .Include(u => u.User)
                    .Include(u => u.MemePictures)
                    .FirstOrDefault();
            }
            else
            {
                meme = _context.Memes
                    .Where(m => m.Id == id && m.IsApproved == true)
                    .Include(u => u.User)
                    .Include(u => u.MemePictures)
                    .FirstOrDefault();
            }
            if (meme.Id == 0)
                return NotFound("The meme does not exist or has not been approved by the moderator");
            return View(meme);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> PublishMeme(int id)
        {
            var publishedMeme = await _memeService.PublishMeme(id);
            if (!publishedMeme.IsSuccess)
                return BadRequest(publishedMeme.ErrorMessage);
            return RedirectToAction("AdminPanel", "User");
        }
    }
}

Memochka/Views/Meme/CreateMemePage.cshtml
@using Memochka.Models.MemochkaDbContext
@model Memochka.Models.Entities.Meme
@inject MemochkaContext DbContext;
@{
    ViewData["Title"] = "Створити мемас";
    var categories = DbContext.MemeCategories.ToList();
}
<div class="main-container my-5">
    <div class="row">
        <form asp-controller="Meme" asp-action="CreateMeme" enctype="multipart/form-data" class="pt-5 ms-auto">
            <!-- Title input -->
            <div class="form-outline mb-4">
                <label class="form-label" for="titleInput">Назва</label>
                <input asp-for="Title" id="titleInput" class="form-control" />
                <span asp-validation-for="Title" class="text-danger h3" style="font-size: 15px"></span>
            </div>
            <!-- Main Picture input -->
            <div class="form-outline mb-4">
                <label class="form-label" for="mainPictureId">Оберіть головну картинку</label>
                <input id="mainPictureId" name="mainImg" type="file" class="form-control" />
            </div>
            <!-- Origins input -->
            <div class="form-outline mb-4">
                <label class="form-label" for="originsIput">Походження</label>
                <textarea asp-for="Origins" id="originsIput" class="form-control"></textarea>
                <span asp-validation-for="Origins" class="text-danger h3" style="font-size: 15px"></span>
            </div>
            <!-- Origins Picture input -->
            <div class="form-outline mb-4">
                <label class="form-label" for="originsPictureId">Оберіть картинку походження</label>
                <input id="originsPictureId" name="originImg" type="file" class="form-control" />
            </div>
            <!-- Meaning input -->
            <div class="form-outline mb-4">
                <label class="form-label" for="meaningInput">Значення</label>
                <textarea asp-for="Meaning" id="meaningInput" class="form-control"></textarea>
                <span asp-validation-for="Meaning" class="text-danger h3" style="font-size: 15px"></span>
            </div>
            <!-- Year input -->
            <div class="form-outline mb-4">
                <label class="form-label" for="yearInput">Рік створення мему</label>
                <input asp-for="Year" id="yearInput" class="form-control" />
                <span asp-validation-for="Year" class="text-danger h3" style="font-size: 15px"></span>
            </div>
            @*Category Input*@
            <select class="form-select" asp-for="CategoryId" aria-label="Default select example">
                <option selected>Category</option>
                @foreach (var category in categories)
                {
                    <option value="@category.Id">@category.Category</option>
                }
            </select>
            <!-- Multiple memes input -->
            <div class="mb-4">
                <label for="multipleMemesInput" class="form-label">Додайте приклади мемасів!</label>
                <input class="form-control" name="memeImg" type="file" id="multipleMemesInput" multiple>
            </div>
            <!-- Submit button -->
            <button type="submit" asp-action="CreateMeme" class="btn btn-primary btn-block mb-4 w-100">Створити МЕМ</button>
        </form>
    </div>
</div>

Memochka/Views/Meme/MemePage.cshtml
@using Microsoft.EntityFrameworkCore
@using Memochka.Models.MemochkaDbContext
@model Memochka.Models.Entities.Meme
@inject MemochkaContext DbContext
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = Model.Title;
    int temp = 1;
    var memes = DbContext.Memes
        .Where(m=>m.IsApproved==true)
        .OrderByDescending(m => m.Views).Take(5).ToList();
    string picTemp = Model.MemePictures[0].PictureId;
}

<div class="main-container my-5">
    <div class="row border p-3">
        <div class="d-flex align-items-center">
            <h1>@Model.Title</h1>
        </div>
    </div>
    <div class="row">
        @* Modal*@
        <div class="modal fade" id="addPostModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="exampleModalLabel">Додати пост</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body d-flex justify-content-center border p-1">
                        <div style="background: white; width: 50%">
                            <a role="button" asp-controller="Meme" asp-action="CreateMemePage" class="d-flex flex-wrap text-center mx-auto btn">
                                <img src="/images/LoginImage.jpg" style="width: 150px;height: 150px" class="mx-auto" />
                                <p style="font-size: 20px; font-weight: 500; padding: 10px 20px; background: black; color: white" class="mt-5 text-center mx-auto">Додати мемчик</p>
                            </a>
                        </div>
                        <div style="background: black; color: white; width: 50%">
                            <a role="button" asp-controller="Article" asp-action="CreateArticlePage" class="d-flex flex-wrap text-center mx-auto btn">
                                <img src="/images/WhitePensil.png" style="width: 150px;height: 150px" class="mx-auto" />
                                <p style="font-size: 20px; font-weight: 500; padding: 10px 20px; background: white; color: black" class="mt-5 text-center mx-auto">Написати статтю</p>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @*Left Side*@
        <div class="col-xl-8 col-lg-8 col-md-12 d-inline border-end">
            <div class="d-block">
                <div class="d-flex text-center align-items-center">
                    <img class="rounded-circle" style="height: 40px;width: 40px; margin-bottom: 0!important" src="@($"/images/users/{Model.User.Id}.jpg")" /s>
                    <p style="font-size: 20px; font-weight: 500; margin-bottom: 0!important" class="mx-3 text-center">@Model.User.Nickname</p>
                    <p class="text-secondary" style="margin-bottom: 0!important">@($"{Model.PublicationDate.ToString("g")}")</p>
                    <div class="ms-auto d-flex">
                        <i class="ms-2 bi bi-eye" style="max-width: 20px; max-height: 18px; margin-bottom: 4px"></i>
                        <p class="ms-1">@Model.Views</p>
                    </div>
                </div>
                <div class="mt-3">
                    <img style="max-width:100%; height:auto;" src="@($"/images/memes/{Model.Id}MainImg.jpg")" />
                </div>
                <div class="mt-3">
                    <h1>Походження</h1>
                    <p>@Model.Origins</p>
                    <img class="mt-1 w-100" src="@($"/images/memes/{Model.Id}OriginImg.jpg")" />
                </div>
                <div class="mt-3">
                    <h1>Значення</h1>
                    <p>@Model.Meaning</p>
                </div>
                @*Slider*@
                <div id="carouselExampleCaptions" class="carousel slide mx-auto mt-5">
                    <div class="carousel-inner">
                        @foreach (var item in Model.MemePictures)
                        {
                            <div class="carousel-item @(item.PictureId == picTemp ? "active" : "")">
                                <img src="@Url.Content($"~/images/memes/{item.PictureId}")" class="d-block w-100 img-fluid" alt="...">
                            </div>
                        }
                    </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                    </button>
                </div>
            </div>
        </div>
        @*Right Side*@
        <div class="col-xl-4 col-lg-4 col-md-12 d-inline">
            <div class=" d-block p-2 border mt-3">
                <div class="rounded-circle bg-black mx-auto" style="max-width: 100px; max-height: 100px">
                    <img src="/images/WhitePensil.png" class="p-3" />
                </div>
                <div class="d-flex mt-3 mb-3 align-content-center flex-wrap">
                    <p class="my-2 mx-auto" style="font-size: 30px; font-weight: 700">Стань автором!</p>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <a role="button" data-bs-toggle="modal" data-bs-target="#addPostModal" aria-disabled="true" class="btn btn-dark mt-3 mx-auto" style="font-size: 20px; font-weight: 500; padding: 10px 20px;">Написати пост</a>
                    }
                    else
                    {
                        <a role="button" asp-controller="User" asp-action="Login" aria-disabled="true" class="btn btn-dark mt-3 mx-auto" style="font-size: 20px; font-weight: 500; padding: 10px 20px;">Написати пост</a>
                    }
                </div>
            </div>
            @*Popular Memes*@
            <div class="justify-content-center text-center mt-5">
                <h4 class="fw-bold ">ПОПУЛЯРНІ МЕМЧИКИ!!!</h4>
                @foreach(var meme in memes)
                {
                    <div class="d-flex justify-content-center">
                        <a class="d-flex text-decoration-none justify-content-center" asp-controller="Meme" asp-action="MemePage" asp-route-id="@meme.Id">
                            <div class="card text-light m-3 mb-0 d-flex align-items-center" style="border-width: 0">
                                <img src="@($"/images/memes/{meme.Id}MainImg.jpg")" class="card-img d-block " style="width: 90%; max-height: 100%; max-width: 100%">
                                <div class="card-img-overlay d-flex align-items-start">
                                    <span class="badge bg-primary me-auto ms-2" style="font-size: 19px; border-radius: 50%">@(temp++)</span>
                                </div>
                                <p class="text-black me-auto ms-3 mt-1 mb-0" style="font-size: 17px; font-weight: 600">@meme.Title</p>
                            </div>
                        </a>
                    </div>
                    
                }
            </div>
        </div>
    </div>
</div>

Memochka/Views/Meme/Memes.cshtml
@using Memochka.Models.MemochkaDbContext
@model List<Memochka.Models.Entities.Meme>
@inject MemochkaContext DbContext
@{
    ViewData["Title"] = "Мемчики";
    // Top 10 News List
    var sections = DbContext.MemeCategories
        .Select(c => c.Category).ToList();
    var years = new List<int>()
    {
        2007,
        2008,
        2009,
        2010,
        2011,
        2012,
        2013,
        2014,
        2015,
        2016,
        2017,
        2018,
        2019,
        2020,
        2021,
        2022,
        2023
    };
}
<div class="main-container my-5">
    <div class="row border p-3">
        <div class="d-flex align-items-center">
            <h1>Мемчики</h1>
            <div class="d-block ms-auto align-items-center border p-1">
                <p class="mx-auto ps-1" style="font-size: 20px; font-weight: 600; margin-bottom: 0">Стань автором!</p>
                @if (User.Identity.IsAuthenticated)
                {
                    <a role="button" data-bs-toggle="modal" data-bs-target="#addPostModal" aria-disabled="true" class="btn btn-dark mx-auto" style="font-size: 20px; font-weight: 500; padding: 4px 8px;">Написати пост</a>
                }
                else
                {
                    <a role="button" asp-controller="User" asp-action="Login" aria-disabled="true" class="btn btn-dark mx-auto" style="font-size: 20px; font-weight: 500; padding: 4px 8px;">Написати пост</a>
                }
            </div>
        </div>
    </div>
    <div class="row">
        @* Modal*@
        <div class="modal fade" id="addPostModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="exampleModalLabel">Додати пост</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body d-flex justify-content-center border p-1">
                        <div style="background: white; width: 50%">
                            <a role="button" asp-controller="Meme" asp-action="CreateMemePage" class="d-flex flex-wrap text-center mx-auto btn">
                                <img src="/images/LoginImage.jpg" style="width: 150px;height: 150px" class="mx-auto" />
                                <p style="font-size: 20px; font-weight: 500; padding: 10px 20px; background: black; color: white" class="mt-5 text-center mx-auto">Додати мемчик</p>
                            </a>
                        </div>
                        <div style="background: black; color: white; width: 50%">
                            <a role="button" asp-controller="Article" asp-action="CreateArticlePage" class="d-flex flex-wrap text-center mx-auto btn">
                                <img src="/images/WhitePensil.png" style="width: 150px;height: 150px" class="mx-auto"/>
                                <p style="font-size: 20px; font-weight: 500; padding: 10px 20px; background: white; color: black" class="mt-5 text-center mx-auto">Написати статтю</p>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @*Left Side*@
        <div class="col-xl-4 col-lg-4 col-md-12 d-inline border-end">
            @*Popular Memes*@
            <div class="justify-content-center text-center mt-5">
                <h4 class="fw-bold ">Мемаси за розділом</h4>
                <div class="nav justify-content-evenly">
                    @foreach (var sect in sections)
                    {
                        <a asp-controller="Meme" asp-action="Memes" asp-route-category="@sect" class="nav-link">@sect</a>
                    }
                </div>
                <h4 class="fw-bold mt-3">Мемаси за роком</h4>
                <div class="nav justify-content-evenly">
                    @foreach (var year in years)
                    {
                        <a asp-controller="Meme" asp-action="Memes" asp-route-year="@year" class="nav-link">@year</a>
                    }
                </div>
            </div>
        </div>

        @*Right Side*@
        <div class="col-xl-8 col-lg-8 col-md-12 d-inline">
            <div class="d-flex flex-wrap">
                @foreach(var meme in Model)
                {
                    <div class="d-block mb-3 mt-2 memes-container h-100">
                        <a role="button" class="text-decoration-none w-100 h-100" asp-controller="Meme" asp-action="MemePage" asp-route-id="@meme.Id">
                            <img src="@($"/images/memes/{meme.Id}MainImg.jpg")" style="width: 90%; height: 90%" />
                            <p class="mb-3 ms-md-2 text-black" style="font-size: 18px; font-weight: 500">@meme.Title</p>
                        </a>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

Memochka/Views/Meme/MemesOffer.cshtml
@using Microsoft.EntityFrameworkCore
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using Memochka.Models.MemochkaDbContext
@model Memochka.Models.Entities.Meme
@inject MemochkaContext DbContext
@{
    ViewData["Title"] = "Запропонушка";
    // Top 10 News List
    int temp = 1;
    var memes5 = DbContext.Memes
        .Where(m => m.IsApproved == true)
        .OrderByDescending(m => m.Views).Take(5).ToList();
    var memes = DbContext.Memes
        .Include(m=>m.User)
        .OrderByDescending(m => m.PublicationDate);
}
<div class="main-container my-5">
    <div class="row border p-3">
        <div class="d-flex align-items-center">
            <h1>Запропонушка</h1>
        </div>
    </div>
    <div class="row">
        @* Modal*@
        <div class="modal fade" id="addPostModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="exampleModalLabel">Додати пост</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body d-flex justify-content-center border p-1">
                        <div style="background: white; width: 50%">
                            <a role="button" asp-controller="Meme" asp-action="CreateMemePage" class="d-flex flex-wrap text-center mx-auto btn">
                                <img src="/images/LoginImage.jpg" style="width: 150px;height: 150px" class="mx-auto" />
                                <p style="font-size: 20px; font-weight: 500; padding: 10px 20px; background: black; color: white" class="mt-5 text-center mx-auto">Додати мемчик</p>
                            </a>
                        </div>
                        <div style="background: black; color: white; width: 50%">
                            <a role="button" asp-controller="Article" asp-action="CreateArticlePage" class="d-flex flex-wrap text-center mx-auto btn">
                                <img src="/images/WhitePensil.png" style="width: 150px;height: 150px" class="mx-auto" />
                                <p style="font-size: 20px; font-weight: 500; padding: 10px 20px; background: white; color: black" class="mt-5 text-center mx-auto">Написати статтю</p>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @*Left Side*@
        <div class="col-xl-8 col-lg-8 col-md-12 d-inline border-end">
            <div class="d-block">
                @foreach (var meme in memes)
                {
                    <div class="d-block mb-3 mt-2 w-100 border">
                        <a role="button" class="text-decoration-none p-1" asp-controller="Meme" asp-action="MemePage" asp-route-id="@meme.Id">
                            <p class="mb-2 ms-md-2 text-black" style="font-size: 30px; font-weight: 600">@meme.Title</p>
                            <img src="@($"/images/memes/{meme.Id}MainImg.jpg")" style="width: 90%; height: 90%" />
                        </a>
                        <div class="d-flex mt-3 p-1">
                            <img src="@($"/images/users/{meme.UserId}.jpg")" class="me-3 my-auto rounded-circle" style="height: 45px; width: 45px" />
                            <p class="my-auto" style="font-weight: 600; font-size: 20px">@meme.User.Nickname</p>
                            <p class="my-auto ms-2 text-secondary" style="font-size: 13px">@meme.PublicationDate.ToString("g")</p>
                        </div>
                    </div>
                }
            </div>
        </div>
        @*Right Side*@
        <div class="col-xl-4 col-lg-4 col-md-12 d-inline">
            <div class=" d-block p-2 border mt-3">
                <div class="rounded-circle bg-black mx-auto" style="max-width: 100px; max-height: 100px">
                    <img src="/images/WhitePensil.png" class="p-3"/>
                </div>
                <div class="d-flex mt-3 mb-3 align-content-center flex-wrap">
                    <p class="my-2 mx-auto" style="font-size: 30px; font-weight: 700">Стань автором!</p>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <a role="button" data-bs-toggle="modal" data-bs-target="#addPostModal" aria-disabled="true" class="btn btn-dark mt-3 mx-auto" style="font-size: 20px; font-weight: 500; padding: 10px 20px;">Написати пост</a>
                    }
                    else
                    {
                        <a role="button" asp-controller="User" asp-action="Login" aria-disabled="true" class="btn btn-dark mt-3 mx-auto" style="font-size: 20px; font-weight: 500; padding: 10px 20px;">Написати пост</a>
                    }
                </div>
            </div>
            @*Popular Memes*@
            <div class="justify-content-center text-center mt-5">
                <h4 class="fw-bold ">ПОПУЛЯРНІ МЕМЧИКИ!!!</h4>
                @foreach (var meme in memes5)
                {
                    <div class="d-flex justify-content-center">
                        <a class="d-flex text-decoration-none justify-content-center" asp-controller="Meme" asp-action="MemePage" asp-route-id="@meme.Id">
                            <div class="card text-light m-3 mb-0 d-flex align-items-center" style="border-width: 0">
                                <img src="@($"/images/memes/{meme.Id}MainImg.jpg")" class="card-img d-block " style="width: 90%; max-height: 100%; max-width: 100%">
                                <div class="card-img-overlay d-flex align-items-start">
                                    <span class="badge bg-primary me-auto ms-2" style="font-size: 19px; border-radius: 50%">@(temp++)</span>
                                </div>
                                <p class="text-black me-auto ms-3 mt-1 mb-0" style="font-size: 17px; font-weight: 600">@meme.Title</p>
                            </div>
                        </a>
                    </div>

                }
            </div>
        </div>
    </div>
</div>